### ISSUE TITLE
cannot open file /proc/fb on Ubuntu on Windows 10

### ISSUE THREAD

**Issue by Log1x** [KittyKatt/screenFetch#449]
Hey there.

Just installed the latest Windows 10 after being hesitant to switch to Windows 10 for quite awhile now.

Bash for Windows is a breath of fresh air compared to using alternatives like Cygwin (Babun).

I grabbed screenfetch off the Ubuntu [repository](https://launchpad.net/%7Edjcj/+archive/ubuntu/screenfetch) and all works well except I'm getting a fatal error for `/proc/fb`.

```
awk: fatal: cannot open file `/proc/fb' for reading (No such file or directory)
/usr/bin/screenfetch: line 1341: [: =: unary operator expected
```

![screenshot](http://i.imgur.com/JWkHVlu.png)

I'm guessing this is due to Bash not being able to detect a GPU? Is there a way to fix this?

Thanks in advance.

EDIT: Sorry for the initial title. Was typing `clear` in my terminal and it happen to go into GitHub's issue title and submit. 😿

**Comment by Log1x** [comment]
Appears this was fixed in the latest [commit](https://github.com/KittyKatt/screenFetch/commit/c72f75b971cc8156a1d92ad776a674d4c013e41f) -- anyway we can get this pushed to Launchpad?

Thanks!

**Comment by darealshinji** [comment]
PPA was updated.

**Comment by Zachswan1** [comment]
Issue still persists for me. Using latest release available on LaunchPad.

**Comment by darealshinji** [comment]
@Zachswan1 New update on PPA should fix that

**Comment by hubdows** [comment]
Issue still persists with version 3.8.0-2~trusty.

awk: fatal: cannot open file `/proc/fb' for reading (No such file or directory)

**Comment by ILikeH8** [comment]
Yup still no gpu showing up after installing and updating the ppa.

**Comment by Pablo1107** [comment]
I have ArchWSL and this happens to me too. Any fix?

**Comment by dahsameer** [comment]
@Pablo1107, dc72b5932e86ba9c4e36110408690abeb2004070 this commit fixed it for me

**Comment by darealshinji** [comment]
Good point, that commit should have fixed it.

**Comment by Xmetalfanx** [comment]
I can't comment on this exact issue, but I think it was on 16.04 (Ubuntu ..) based releases the default version of Screenfetch in the repos is not the newest version ... I wonder in some cases some of these issues ... heck i see "trusty" aka 14.04 in that screenshot ... are being caused by people running an older version of screenfetch before commits that fixed different issues were included.

**Comment by Pablo1107** [comment]
@dahsameer the latest version on the arch repo is screenfetch 3.8.0-2, when that commit was released?

**Comment by darealshinji** [comment]
Maybe adding a template that tells the user he/she should check the latest version from git before making a bug report would help.
